image: python:3.10

test_backend:
  script:
  - export TOGETHER_API_KEY=$(cat backend/src/ci_cd_resources/together_api_key)
  - pip install -r backend/src/requirements.txt
  - python backend/src/test_run_sim.py 2 ci_car_sale_simulation